### ISSUE TITLE
[RFC] Avoid enforcing BBMULTICONFIG

### ISSUE THREAD

**Issue by agherzan** [aehs29/meta-freertos#7]
Merely pulling this layer into a build forces a user to have a multi config setup. Having a muticonf example could be useful, but enforcing it at the level of the `layer.conf` seems unnecessary and should be left at the discretion of a user configuration. My proposal would be to remove defining `BBMULTICONFIG` in `layer.conf` and document its definition so a user can decide and add it for example in his `local.conf` based on specific needs.

**Comment by aehs29** [comment]
This sounds reasonable, enabling multiconfig was initially used to show its capabilities and showing an actual example of it, I do understand that there's no need for it to be on the default case, I think commenting out the BBMULTICONFIG line on the layer.conf but keeping the multiconf directory should suffice, those who want to enable it already have a working conf and those who dont wont get it by default

**Comment by aehs29** [comment]
Fixed: https://github.com/aehs29/meta-freertos/commit/c52346aebe8ce628110311bd60ddd8eb75e68fb2

**Comment by agherzan** [comment]
Thanks, @aehs29. This is really helpful.
